import profilePic from './img/profile.jpg';

export const person = {
  basics: {
    name: 'Maxime Choffat',
    label: 'online_sysops',
    picture: profilePic,
    email: 'maxime.choffat@gmail.com',
    phone: '+33 6 33 56 36 25',
    summary: 'my_summary',
    location: {
      address: '5128 rue Saint Andre',
      postalCode: 'H2J 3A7',
      city: 'Montréal',
      countryCode: 'CANADA',
      region: 'Québec',
    },
    profiles: [
      {
        network: 'GitHub',
        username: 'MrRandol',
        url: 'https://github.com/MrRandol',
      },
      {
        network: 'Twitter',
        username: 'Mr_Randol',
        url: 'https://twitter.com/Mr_Randol',
      },
      {
        network: 'LinkedIn',
        username: 'maxime-choffat',
        url: 'https://www.linkedin.com/in/maxime-choffat-b2423a75/',
      },
    ]
  },
  skills: [
    { type: "language", name: "JavaScript", level: "75" },
    { type: "language", name: "Java", level: "60" },
    { type: "language", name: "C#", level: "50" },
    { type: "language", name: "Bash", level: "70" },
    { type: "language", name: "HTML / CSS", level: "75" },
    { type: "language", name: "Python", level: "50" },
    { type: "language", name: "Ruby On Rails", level: "40" },
    { type: "tools", name: "Jenkins", level: "95" },
    { type: "tools", name: "Nexus", level: "95" },
    { type: "tools", name: "Docker", level: "85" },
    { type: "tools", name: "Gitlab", level: "95" },
    { type: "tools", name: "Bitbucket", level: "95" },
    { type: "tools", name: "Jira", level: "90" },
    { type: "tools", name: "Confluence", level: "90" },
    { type: "tools", name: "SonarQube", level: "85" },
    { type: "tools", name: "Kubernetes", level: "75" },
    { type: "webserver", name: "Nginx", level: "95" },
    { type: "webserver", name: "Tomcat", level: "90" },
    { type: "webserver", name: "WildFly", level: "60" },
    { type: "webserver", name: "NodeJs", level: "80" },
    { type: "webserver", name: "Geoserver", level: "75" },
    { type: "webserver", name: "MySQL", level: "85" },
    { type: "webserver", name: "PostgreSQL", level: "80" },
    { type: "webserver", name: "ElasticSearch", level: "75" },
    { type: "framework", name: "OpenScales", level: "95" },
    { type: "framework", name: "OpenLayers", level: "85" },
    { type: "framework", name: "ReactJs", level: "85" },
    { type: "framework", name: "Angular", level: "85" },
    { type: "devTool", name: "Maven", level: "90" },
    { type: "devTool", name: "Gradle", level: "70" },
    { type: "devTool", name: "Git", level: "95" },
    { type: "devTool", name: "Mercurial", level: "95" },
    { type: "devTool", name: "Ansible", level: "75" },
    { type: "softSkill", name: "Agile", level: "90" },
    { type: "softSkill", name: "DevOps", level: "95" },
    { type: "softSkill", name: "GestionDeProjet", level: "60" },
    { type: "softSkill", name: "SIG", level: "90" }
  ],
  work: [
    {
      company: 'Ubisoft Montréal',
      logo: 'img:https://static-wordpress.akamaized.net/montreal.ubisoft.com/wp-content/uploads/2018/10/03173820/Logo_Ubi_Stacked_HOR_Montreal_WHITE.png',
      position: 'online_sysops',
      website: 'https://montreal.ubisoft.com/',
      startDate: '2019-06',
      endDate: 'Today',
      summary: "ubisoft_summary",
      highlights: [
        'JavaScript',
        'C#',
        'Python',
        'Angular',
        'Jira',
        'Confluence',
        'Kubernetes',
        'Gitlab',
        'Docker',
        'Git',
        'Agile',
        'DevOps',
        'Analysis',
        'Architecture'
      ],
    },
    {
      company: 'SII Canada',
      logo: 'img:https://www.siicanada.com/public/header/logo.png',
      position: 'devops_cata_inte',
      website: 'https://www.siicanada.com/',
      startDate: '2019-01',
      endDate: '2019-06',
      summary: "sii_summary",
      highlights: [
        'Jenkins',
        'SonarQube',
        'Nexus',
        'Jira',
        'Bitbucket',
        'Confluence',
        'Nginx',
        'Ansible',
        'Git',
        'Maven',
        'Gradle',
        'Agile',
        'DevOps',
        'Analysis',
        'Architecture',
        'Training'
      ],
    },
    {
      company: 'Nalys',
      logo: 'img:https://www.nalys-group.com/theme/default-2017/img/logo.png',
      position: 'internal_cluster_build',
      website: 'https://www.nalys-group.com/en/home',
      startDate: '2018-06',
      endDate: '2018-08',
      summary: 'nalys_internal_summary',
      highlights: [
        'Jenkins',
        'SonarQube',
        'Nexus',
        'Gitlab',
        'Jira',
        'Kubernetes',
        'Docker',
        'Git',
        'Maven',
        'Agile',
        'Devops'
      ]
    },
    {
      company: 'Nalys',
      logo: 'img:https://www.nalys-group.com/theme/default-2017/img/logo.png',
      position: 'Nalys Graduate Program',
      website: 'https://www.nalys-group.com/en/home',
      startDate: '2018-09',
      summary: 'nalys_graduate_program_summary',
      highlights: [
        'Agile',
        'Devops',
        'Training'
      ]
    },
    {
      company: 'ING (Nalys)',
      logo: 'img:https://www.nalys-group.com/theme/default-2017/img/logo.png',
      position: 'release_engineer',
      website: 'http://piedpiper.com',
      startDate: '2017-06',
      endDate: '2018-06',
      summary: 'nalys_ing_summary',
      highlights: [
        'Jenkins',
        'SonarQube',
        'Artifactory',
        'Gitlab',
        'Jira',
        'Conluence',
        'TFS',
        'Git',
        'Maven',
        'Gradle',
        'Agile',
        'Devops'
      ]
    },
    {
      company: 'GIM (Nalys)',
      logo: 'img:https://www.nalys-group.com/theme/default-2017/img/logo.png',
      position: 'developer_devops_coach',
      website: 'https://www.gim.be/en',
      startDate: '2017-02',
      endDate: '2017-05',
      summary: 'nalys_gim_summary',
      highlights: [
        'JavaScript',
        'Java',
        'OpenLayers',
        'Jenkins',
        'Nexus',
        'Gitlab',
        'Git',
        'Maven',
        'Docker',
        'Nginx',
        'Geoserver',
        'Wildfly',
        'Agile',
        'DevOps',
        'SIG',
        'Training',
      ]
    },
    {
      company: 'Worldline',
      logo: 'img:https://worldline.com/content/dam/gotomarket/logo/logo-worldline.png',
      position: 'project_manager',
      website: 'https://worldline.com/',
      startDate: '2016-12',
      endDate: '2015-07',
      summary: 'worldline_project_manager_summary',
      highlights: [
        "Agile",
        "DevOps",
        "Project Management",
        "Architecture",
        'SIG'
      ]
    },
    {
      company: 'Worldline',
      logo: 'img:https://worldline.com/content/dam/gotomarket/logo/logo-worldline.png',
      position: 'application_manager',
      website: 'https://worldline.com/',
      startDate: '2012-09',
      endDate: '2015-06',
      summary: 'worldline_application_manager_summary',
      highlights: [
        "Flex",
        "JavaScript",
        "Java",
        "Bash",
        "Nginx",
        "Tomcat",
        "NodeJs",
        "Geoserver",
        "Rok4",
        "OpenScales",
        "ReactJs",
        "Cucumber",
        "PostgreSQL (PostGIS)",
        "MySQL",
        "ElasticSearch",
        "Redis",
        "Maven",
        "Git",
        "Docker",
        "Vagrant",
        "Jenkins",
        "Nexus",
        "Jira",
        "Agile",
        "DevOps",
        "SIG",
        "Architecture"

      ]
    },
    {
      company: 'Worldline',
      logo: 'img:https://worldline.com/content/dam/gotomarket/logo/logo-worldline.png',
      position: 'flex_developer',
      website: 'https://worldline.com/',
      startDate: '2012-02',
      endDate: '2012-08',
      summary: 'worldline_flex_summary',
      highlights: [
        "Flex",
        "JavaScript",
        "Java",
        "Bash",
        "Nginx",
        "Tomcat",
        "OpenScales",
        "Mercurial",
        "Maven",
        "Jenkins",
        "Jira",
        "Nexus",
        'SIG'
      ]
    },
    {
      company: 'Captive Studio',
      logo: 'img:https://pbs.twimg.com/profile_images/1112815436909985793/_1klXiWS_400x400.png',
      position: 'web_developer',
      website: 'https://www.captive.fr/',
      startDate: '2010-08',
      endDate: '2011-02',
      summary: 'captive_studio_summary',
      highlights: [
        "Ruby On Rails",
        "MySQL",
        "Agile",
        "Extreme Programming"
      ]
    }
  ],
  education: [
    {
      institution: 'UTBM (Université de Technologie de Belfort Montbéliard), France',
      logo: 'img:https://pbs.twimg.com/profile_images/673805187400749056/18OZaqMO_400x400.png',
      website: 'https://www.utbm.fr/',
      area: 'utbm_area',
      studyType: 'utbm_studytype',
      startDate: '2007-09',
      endDate: '2012-06',
      gpa: '0.0',
      courses: [
        'education_english_course'
      ],
    },
    {
      institution: 'Lycée Saint André - Colmar, France',
      area: 'st_andre_area',
      studyType: 'st_andre_studytype',
      startDate: '2003-08',
      endDate: '2004-05',
      gpa: '0.0',
      courses: [
        'education_spe_math'
      ],
    }
  ],
  interests: [
    {
      name: 'Hobbies',
      keywords: [
        'hobby_high_tech',
        'hobby_travel',
      ],
    },
    {
      name: 'Sports',
      keywords: [
        'sport_fencing',
        'sport_judo',
      ],
    },
  ],
  languages: [
    {
      name: 'french',
      level: 'native_speaker',
    },
    {
      name: 'english',
      level: 'fluent',
    },
  ]
};
